language: cpp
dist: trusty
sudo: required

matrix:
  include:

  - os: linux
    compiler: gcc
    env: COMPILER=g++-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8', 'ninja-build']

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config Release -- -j2
  - ctest -C Release -V -j