language: cpp
dist: trusty
sudo: required

matrix:
  include:

### LINUX + GCC ################################################################

  - os: linux
    compiler: gcc
    env:
      - COMPILER=g++-9
      - CXXFLAGS=-std=c++2a
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9']

  - os: linux
    compiler: gcc
    env: COMPILER=g++-9
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-9']

  - os: linux
    compiler: gcc
    env: COMPILER=g++-8
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-8']

### LINUX + CLANG ##############################################################

  - os: linux
    compiler: clang
    env: COMPILER=clang++-7
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-7']
        packages: ['clang-7']

### OSX + GCC ##################################################################

  - os: osx
    osx_image: xcode11.2
    compiler: gcc

  - os: osx
    osx_image: xcode10.2
    compiler: gcc

### OSX + CLANG ################################################################

  - os: osx
    osx_image: xcode11.2
    compiler: clang

  - os: osx
    osx_image: xcode10.2
    compiler: clang

### BUILD ######################################################################

script:
  - |
    # Configure build variables
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      if [[ "${COMPILER}" != "" ]]; then
        export CXX=${COMPILER};
      fi
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "${COMPILER}" != "" ]]; then
        export CXX=${COMPILER};
      fi
    fi

  - uname -a
  - $CXX --version

  - mkdir build
  - cd build
  
  - cmake ..
  - cmake --build .
  
  - ctest